### ISSUE TITLE
add CNAME file so that URL appears as spidal.org

### ISSUE THREAD

**Issue by orbeckst** [DSC-SPIDAL/www#5]
Although we have the http://spidal.org/ domain name, we get forwarded to http://dsc-spidal.github.io/www/.

This looks ugly. The simple solution is to add a `CNAME` file, see https://help.github.com/articles/setting-up-an-apex-domain-and-www-subdomain/

(For http://mdanalysis.org we have the [CNAME](https://github.com/MDAnalysis/MDAnalysis.github.io/blob/master/CNAME) file

```
www.mdanalysis.org
```

which gives us both http://www.mdanalysis.org and the apex domain http://mdanalysis.org.)

**Comment by orbeckst** [comment]
(I don't want to do this as a PR because you might have to exercise some judgment and possibly also fiddle with the DNS... _read the GitHub help pages first_.)

**Comment by laszewsk** [comment]
yes this is on our things to do. I just wanted to get this out ASAP. 
The other way would be keep it in git this way and just do a nighty update on spidal.org http://spidal.org/ which is actually a real machine or vm.

**Comment by orbeckst** [comment]
I wouldn't bother with the nightly sync – these static pages are so light-weight that it doesn't need on a dedicated machine. And GitHub is probably more resilient than a single machine. The CNAME switch worked really well for us in the past. GitHub does all the DNS magic.

**Comment by orbeckst** [comment]
>  I just wanted to get this out ASAP.

Yes, I totally agree.

**Comment by laszewsk** [comment]
yes our preferred suggestion was CNAME switch.
I will put it on the list of things to do.

**Comment by orbeckst** [comment]
@wigginst , did you decide not to use CNAME, despite of what @laszewsk said?

**Comment by wigginst** [comment]
I assumed that it was implemented, since the old spidal.org domain now
automatically redirects to the spidal git site.

**Comment by orbeckst** [comment]
The issue was about something else: keep spidal.org in the URL bar instead of the GitHub URL (the one like www-dsc...io). See the links I provided. 

An example is http://MDAnalysis.org which is actually completely GitHub hosted but does not appear as such. 

## 

Oliver Beckstein
email: orbeckst@gmail.com

> Am Jul 9, 2016 um 3:49 schrieb wigginst notifications@github.com:
> 
> I assumed that it was implemented, since the old spidal.org domain now
> automatically redirects to the spidal git site.

**Comment by wigginst** [comment]
Sounds interesting. I will see about taking care of this on Monday.

**Comment by laszewsk** [comment]
Tom did not understand what you meant, yes we want to use cname. 

so this issue will stay open till this is done.

**Comment by laszewsk** [comment]
Tom. Please do not do this as I think this has to be done by Allen. Please coordinate with Julie first.

We will eventually have this done, but at this time Allan has set up a simple forward till he has time to do this right. There is some work that needs to be done, but I think at this time its just more important to get all the contents over. Please coordinate with Julie.

**Comment by wigginst** [comment]
Very well, I won't touch the address on my own.

**Comment by orbeckst** [comment]
This seems to be working now, eg http://www.spidal.org/bib.html
